sudo: false
branches:
  only:
    - master
language: python
python:
  - "2.7"
  - "3.4"
env:
  - TESTS=float32
  - TESTS=float64
before_install:
  - |
      # Setup Python environment with BLAS libraries
      wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
      chmod +x miniconda.sh
      ./miniconda.sh -b
      export PATH=$HOME/miniconda/bin:$PATH
      conda update -q --yes conda
install:
  # Install all Python dependencies
  - |
      conda install -q --yes python=$TRAVIS_PYTHON_VERSION mkl bokeh nose numpy pip coverage six scipy
      pip install -q --no-deps git+git://github.com/Theano/Theano.git # Development version
      pip install -q nose2[coverage-plugin] coveralls
script:
  - |
      python setup.py install # Tests setup.py (should also install dill)
      # Must export environment variable so that the subprocess is aware of it
      export THEANO_FLAGS=floatX=$TESTS
      # Running nose2 within coverage makes imports count towards coverage
      bokeh-server &> /dev/null &
      coverage run --source=blocks -m nose2.__main__ -v tests
after_script:
  - coveralls
